import React from "react";
import Head from "next/head";
import ProjectPage from "../../Views/ProjectPage";
import { useRouter } from "next/router";
const projectsidx = () => {
  const router = useRouter();
  const { projectsidx } = router.query;
  // console.log(projectsidx);
  return (
    <>
      {" "}
      {/* <Head>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css?family=Montserrat'
        />
         metatag google 
         <meta
          name='description'
          content='We are expert in turning your brand into the catchy icon'
        />
        <meta
          name='keywords'
          content='Agency, Content,Marketing, KOL, Festival, Singer, Video, Art, Products'
        />
        <meta name='author' content='Trum Agency' />
        <link rel='canonical' href='/projects' />
        metatag facebook
        <meta property='og:url' content='https://www.trumagency.com/projects' />
        <meta property='og:type' content='article' />
        <meta property='og:title' content='Trum Agency' />
        <meta
          property='og:description'
          content='We are expert in turning your brand into the catchy icon'
        />
        <meta
          property='og:image'
          content='https://pagesmanagementapi.com/storage/logothumnail.png'
        />
        <meta property='og:image:width' content='1200' />
        <meta property='og:image:height' content='630' />
      </Head> */}
      <ProjectPage projectsidx={projectsidx} />
    </>
  );
};

export default projectsidx;
